import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  toolbar: theme.mixins.toolbar,
  title: {
    marginTop: "3%",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    backgroundClip: "text",
    fontWeight: "800",
    fontSize: "32px",
    textAlign: "center",
    marginBottom: "20px",
    letterSpacing: "2px",
  },
  emptyButton: {
    minWidth: "150px",
    borderRadius: "8px",
    backgroundColor: "#fff",
    color: "#e74c3c",
    fontWeight: "600",
    textTransform: "none",
    borderColor: "#e74c3c",
    height: "44px",
    transition: "all 0.3s ease",
    '&:hover': {
      backgroundColor: "#e74c3c",
      color: "white",
      borderColor: "#e74c3c",
    },
    [theme.breakpoints.down("xs")]: {
      marginBottom: "5px",
    },
    [theme.breakpoints.up("xs")]: {
      marginRight: "20px",
    },
  },
  checkoutButton: {
    minWidth: "150px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    height: "44px",
    borderRadius: "8px",
    fontWeight: "600",
    textTransform: "none",
    fontSize: "14px",
    transition: "all 0.3s ease",
    '&:hover': {
      background: "linear-gradient(135deg, #5a6fd8 0%, #6a4190 100%)",
      transform: "translateY(-2px)",
      boxShadow: "0 6px 20px rgba(102, 126, 234, 0.3)",
    },
  },
  link: {
    textDecoration: "none",
    color: "#667eea",
    fontWeight: "600",
    transition: "all 0.3s ease",
    '&:hover': {
      color: "#5a6fd8",
      textDecoration: "underline",
    },
  },
  cardDetails: {
    display: "flex",
    marginTop: "7%",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "16px",
  },
  cartContainer: {
    backgroundColor: "white",
    borderRadius: "16px",
    padding: "24px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
    margin: "20px 0",
  },
  emptyCart: {
    textAlign: "center",
    padding: "60px 20px",
    color: "#7f8c8d",
  },
  emptyCartIcon: {
    fontSize: "80px",
    color: "#bdc3c7",
    marginBottom: "20px",
  },
  totalSection: {
    backgroundColor: "#f8f9fa",
    borderRadius: "12px",
    padding: "20px",
    marginTop: "20px",
  },
  totalText: {
    fontSize: "24px",
    fontWeight: "700",
    color: "#2c3e50",
    textAlign: "right",
    margin: "4px 0 !important",
    fontFamily: "Poppins",
  },
}));
